# Generated by Django 5.0.6 on 2024-07-08 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=100)),
                ('release_year', models.IntegerField()),
                ('rating', models.FloatField()),
                ('description', models.TextField()),
                ('trailer_url', models.URLField(blank=True, null=True)),
                ('download_link', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(null=True, upload_to='movies/images/')),
                ('released', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='movie_media.category')),
            ],
        ),
    ]
