# Generated by Django 5.0.6 on 2024-07-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_media', '0002_series_season_episode'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='season',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='season',
            name='series',
        ),
        migrations.RemoveField(
            model_name='series',
            name='category',
        ),
        migrations.AddField(
            model_name='movie',
            name='series',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='Episode',
        ),
        migrations.DeleteModel(
            name='Season',
        ),
        migrations.DeleteModel(
            name='Series',
        ),
    ]
