# Generated by Django 5.0.6 on 2024-07-10 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_media', '0003_alter_season_unique_together_remove_season_series_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='animation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='drama',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='music_video',
            field=models.BooleanField(default=True),
        ),
    ]
