# Generated by Django 5.0.6 on 2024-07-10 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_reply'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
