# Generated by Django 5.0.6 on 2024-07-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='video_file',
        ),
        migrations.AddField(
            model_name='episode',
            name='download_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
